INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (1, '2014-5-4 15:12:50', 0, 'Account_Check', '{\"Account\":\"dandan\",\"Password\":\"silveran\"}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (2, '2014-5-4 15:12:50', 1, 'Account_Check No Account', '{\"Result\":\"Check_Account_No_Account\"}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (3, '2014-5-4 15:16:12', 0, 'Account_Check', '{\"Account\":\"dandan\",\"Password\":\"silveran\"}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (4, '2014-5-4 15:16:12', 3, 'Account_Check Success', '{\"Result\":\"Success\",\"AccountID\":2}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (5, '2014-5-4 15:17:30', 0, 'Account_Check', '{\"Account\":\"dandan\",\"Password\":\"silveran\"}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (6, '2014-5-4 15:17:30', 5, 'Account_Check Success', '{\"Result\":\"Success\",\"AccountID\":2}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (7, '2014-5-4 16:50:28', 0, 'Account_Check', '{\"Account\":\"dandan\",\"Password\":\"silveran\"}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (8, '2014-5-4 16:50:28', 7, 'Account_Check Success', '{\"Result\":\"Success\",\"AccountID\":2}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (9, '2014-5-4 16:51:45', 0, 'Account_Check', '{\"Account\":\"dandan\",\"Password\":\"silveran\"}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (10, '2014-5-4 16:51:45', 9, 'Account_Check Success', '{\"Result\":\"Success\",\"AccountID\":2,\"SessionKey\":\"SessionKey:dandan\"}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (11, '2014-5-4 17:58:08', 0, 'Account_CreatePlayer', '{\"SessionKey\":\"SessionKey:dandan\"}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (12, '2014-5-4 17:58:27', 0, 'Account_CreatePlayer', '{\"SessionKey\":\"SessionKey:dandan\"}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (13, '2014-5-4 17:59:39', 0, 'Account_CreatePlayer', '{\"SessionKey\":\"SessionKey:dandan\"}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (14, '2014-5-6 21:20:52', 0, 'Account_Check', '{\"Account\":\"dandan\",\"Password\":\"silveran\"}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (15, '2014-5-6 21:20:52', 14, 'Account_Check Success', '{\"Result\":\"Success\",\"AccountID\":2,\"PlayerID\":0,\"SessionKey\":\"SessionKey:dandan\",\"ClientAction\":[\"[ToNewPlayer, ]\"]}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (16, '2014-5-6 21:56:28', 0, 'Account_CreatePlayer', '{\"SessionKey\":\"SessionKey:dandan\",\"PlayerName\":\"dandan\"}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (17, '2014-5-6 21:56:32', 16, 'Account_CreatePlayer Success', '{\"PlayerName\":\"dandan\",\"PlayerID\":1}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (18, '2014-5-8 00:38:32', 0, 'Account_CreatePlayer', '{\"SessionKey\":\"SessionKey:dandan\",\"PlayerName\":\"dandan\"}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (19, '2014-5-8 00:38:33', 18, '己有角色存在', '10101');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (20, '2014-5-8 00:43:28', 0, 'Account_CreatePlayer', '{\"SessionKey\":\"SessionKey:dandan\",\"PlayerName\":\"dandan\"}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (21, '2014-5-8 00:43:32', 20, '己有角色存在', '10101');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (22, '2014-5-8 00:44:08', 0, 'Account_CreatePlayer', '{\"SessionKey\":\"SessionKey:dandan\",\"PlayerName\":\"dandan\"}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (23, '2014-5-8 00:44:08', 22, '己有角色存在', '10101');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (24, '2014-5-8 01:17:09', 0, 'Account_Check', '{\"Account\":\"dandan\",\"Password\":\"silveran\"}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (25, '2014-5-8 01:17:13', 24, '成功', '0');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (26, '2014-5-8 01:20:09', 0, 'Account_Check', '{\"Account\":\"dandan\",\"Password\":\"silveran\"}');
INSERT INTO `l_webmethod` (`MethodLogID`, `ActionDate`, `PID`, `MethodName`, `Args`) VALUES (27, '2014-5-8 01:20:09', 26, '成功', '0');
